ci: fixed msrv verification to not include example

diff --git a/.github/workflows/check-and-lint.yaml b/.github/workflows/check-and-lint.yaml
--- a/.github/workflows/check-and-lint.yaml
+++ b/.github/workflows/check-and-lint.yaml
@@ -89,7 +89,6 @@ jobs:
   msrv:
     name: msrv
     runs-on: ubuntu-latest
-    continue-on-error: true
     steps:
       - uses: actions/checkout@v4
       - uses: actions-rs/toolchain@v1
@@ -99,9 +98,5 @@ jobs:
           override: true
       - run: cargo install cargo-msrv
       - name: version_of_cargo_msrv
-        run: cargo msrv --version
-      - name: run_cargo_msrv
-        run: cargo msrv verify --output-format json
-      - name: run_cargo_msrv_on_verify_failure
-        if: ${{ failure() }}
-        run: cargo msrv find --output-format json
+        run: cargo msrv --version > $GITHUB_STEP_SUMMARY
+      - run: cargo msrv verify --output-format json -- ./bisect_msrv.sh && echo "MSRV ok" > $GITHUB_STEP_SUMMARY || echo "MSRV fail" > $GITHUB_STEP_SUMMARY
